---
version: 2
groups:
  security-batch:
    applies-to: "security-updates"
  versioning-batch:
    applies-to: "version-updates"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: pip
    directory: "/python"
    schedule: 
      interval: "weekly"