---
version: 2


updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    dependency-type: "direct"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    dependency-type: "direct"
    schedule:
      interval: "weekly"
    groups:
      versioning-npm-batch:
        applies-to: "version-updates"
        patterns: 
          - "*"
  - package-ecosystem: bundler
    directory: "/ruby"
    dependency-type: "direct"
    schedule:
      interval: "weekly"
  - package-ecosystem: pip
    directory: "/python"
    dependency-type: "direct"
    schedule: 
      interval: "weekly"
    groups:
      versioning-pip-batch:
        applies-to: "version-updates"
        patterns: 
          - "*"
        